### ISSUE TITLE
Fails to connect to latest NATS

### ISSUE THREAD

**Issue by jrbudnack** [cloudfoundry-community/route-registrar-boshrelease#5]
Tried deploying this in CF v250, and found that it couldn't talk to NATS.  Confirmed that I could talk to NATS from the host in question using the command-line.

I realize that the route-registrar has since been folded into CF - Should we update this release with the latest version, or steer people to simply use the one in cf-release?

I get the following error:

```
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32
panic: Failed to connect to NATS bus.

goroutine 16 [running]:
runtime.panic(0x6461c0, 0xc208001140)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/cloudfoundry-incubator/route-registrar/registrar.buildMessageBus(0xc20802b490, 0x7f85b40b1870, 0xc20801a730)
        /var/vcap/packages/route-registrar/src/github.com/cloudfoundry-incubator/route-registrar/registrar/registrar.go:84 +0x68b
github.com/cloudfoundry-incubator/route-registrar/registrar.(*Registrar).RegisterRoutes(0xc20802b490)
        /var/vcap/packages/route-registrar/src/github.com/cloudfoundry-incubator/route-registrar/registrar/registrar.go:39 +0x27
main.main()
        /var/vcap/packages/route-registrar/src/github.com/cloudfoundry-incubator/route-registrar/registrar_app.go:39 +0x43e

goroutine 19 [finalizer wait]:
runtime.park(0x413680, 0x8a0048, 0x89eaa9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x8a0048, 0x89eaa9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

**Comment by drnic** [comment]
Moving repo to attic. See https://github.com/cloudfoundry-incubator/routing-release for CF Core team's release.
